# Predicting a known dataframe
This testset data frame has been carefully removed from the original dataset. We will perform three predictions based on three algorithms namely, Logistic Regression, Binary Classifier and Random Forest Classifier depending upon the training dataset.
The labeled data is already known, we will tally how accurate our result is upon this dataset.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import math
import re

In [3]:
dtf1=pd.read_csv("Rent - Suspected List.csv",names=['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Date', 'Age', 'Area'])
dtf1=dtf1.drop(index=0,axis=0)

In [4]:
dtf1

,Applied,Gender,Payment_Method,Location,Received,Id,Reason,Date,Age,Area
1,$540.00,M,AV,AM,$540.00,GHI001236741,RA,4-Oct-17,40-44,M
2,$500.00,F,AV,AM,$500.00,GHI001236741,RA,13-Oct-17,35-39,M
3,$260.00,M,AV,AM,$260.00,GHI001236741,RA,18-Jan-18,18-19,M
4,$260.00,F,AV,AM,$260.00,GHI001236741,RA,26-Jan-18,20-24,M
5,$540.00,F,RP,AM,$540.00,GHI001236741,RA,5-Nov-18,25-29,M
6,$850.00,F,RP,O,$850.00,GHI001644816,RA,24-Dec-18,25-29,M
7,$620.00,M,AV,O,$620.00,GHI001644816,RA,8-Jan-19,35-39,NE
8,$840.00,M,RP,AM,$840.00,GHI001644816,RA,11-Jan-19,30-34,M
9,$560.00,M,AV,BP,$560.00,GHI001644816,RA,25-Feb-19,25-29,M
10,$640.00,M,AV,BP,$640.00,GHI001644816,RA,8-Mar-19,50-54,NE
11,$740.00,F,AV,W,$740.00,GHI001644816,RA,28-Mar-19,25-29,M
12,$720.00,M,AV,BP,$720.00,GHI001644816,RA,29-Mar-19,30-34,M
13,$570.00,M,AV,BP,$570.00,GHI001644816,RA,17-Apr-19,35-39,M
14,$640.00,M,AV,O,$640.00,GHI001644816,RA,24-Apr-19,40-44,NE
15,"$1,920.00",M,AV,O,"$1,920.00",GHI001644816,RA,14-Jun-19,50-54,NE
16,$620.00,M,AV,BP,$620.00,GHI001644816,RA,20-Jun-19,35-39,NE
17,$660.00,M,AV,BP,$660.00,GHI001644816,RA,27-Jun-19,25-29,NE
18,$720.00,F,RP,O,$720.00,GHI001644816,RA,12-Jul-19,55-59,NE
19,$660.00,F,RP,BP,$660.00,GHI001644816,RA,18-Jul-19,35-39,M
20,$680.00,M,AV,O,$680.00,GHI001644816,RA,5-Sep-19,25-29,M
21,$278.00,M,AV,AM,$278.14,GHI001644816,RA,3-Oct-19,50-54,M
22,$680.00,M,AV,BP,$680.00,GHI001644816,RA,4-Oct-19,35-39,M
23,$602.00,M,AV,AM,$601.86,GHI001644816,RA,4-Oct-19,50-54,M
24,$740.00,F,AV,BP,$740.00,GHI001644816,RA,4-Oct-19,30-34,NE
25,$840.00,F,AV,AM,$840.00,GHI001644816,RA,12-Nov-19,40-44,M
26,$980.00,F,AV,AM,$980.00,GHI001644816,RA,14-Nov-19,40-44,M
27,$800.00,M,AV,AM,$800.00,GHI000183071,RA,9-Jul-18,30-34,M
28,$700.00,M,AV,AM,$700.00,GHI000183071,RA,11-Oct-18,35-39,U
29,$300.00,M,AV,EC,$300.00,GHI001211664,RA,14-Sep-17,20-24,U
30,$300.00,M,AV,EC,$300.00,GHI001211664,RA,12-Dec-17,35-39,M
31,$220.00,F,AV,EC,$220.00,GHI001211664,RA,22-Mar-18,20-24,NE
32,$350.00,M,AV,EC,$350.00,GHI001211664,RA,4-May-18,35-39,M
33,$335.00,F,AV,EC,$335.00,GHI001211664,RA,9-Nov-18,25-29,NE
34,$355.00,M,AV,EC,$355.00,GHI001211664,RA,13-Nov-18,35-39,O
35,$800.00,F,AV,EC,$800.00,GHI001211664,RA,10-Dec-18,65+,NE
36,$320.00,M,AV,EC,$320.00,GHI001211664,RA,13-Dec-18,30-34,NE
37,$500.00,M,RP,O,$500.00,GHI001211664,RA,21-Dec-18,35-39,M
38,$900.00,F,AV,O,$900.00,GHI001211664,RA,4-Jan-19,25-29,M
39,$580.00,M,RP,O,$580.00,GHI001211664,RA,7-Jan-19,30-34,NE
40,$600.00,M,AV,O,$600.00,GHI001211664,RA,9-Jan-19,45-49,M
41,$640.00,M,AV,O,$640.00,GHI001211664,RA,10-Jan-19,60-64,M
42,$860.00,F,AV,O,$860.00,GHI001211664,RA,28-Jan-19,30-34,NE
43,$340.00,F,RP,EC,$340.00,GHI001211664,RA,20-May-19,20-24,M

In [5]:
dtf2=pd.read_csv("concatfd.csv",names=['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Date', 'Age', 'Area'])
dtf2=dtf2.drop(index=0,axis=0)

In [6]:
dtf2

,Applied,Gender,Payment_Method,Location,Received,Id,Reason,Date,Age,Area
1,339,M,AV,AM,339.25,XXXXXXXXXXX,CR,2017-02-09 00:00:00,25-29,O
2,950,F,AV,C,950,XXXXXXXXXXX,CR,2017-02-17 00:00:00,35-39,M
3,1139,GD,RP,BP,1138.5,XXXXXXXXXXX,CR,2017-09-29 00:00:00,45-49,M
4,1650,M,RP,O,1650,XXXXXXXXXXX,RA,2018-05-07 00:00:00,30-34,PP
5,341,F,U,W,341,XXXXXXXXXXX,RA,2018-11-19 00:00:00,20-24,M
6,2915,GD,U,EC,2915.25,XXXXXXXXXXX,RA,2019-02-01 00:00:00,16,NE
7,2599,F,AV,T,2599,XXXXXXXXXXX,RA,2019-03-13 00:00:00,17,O
8,1783,F,AV,N,1782.5,XXXXXXXXXXX,RA,2019-04-10 00:00:00,65+,PP
9,1955,F,AV,S,1955,XXXXXXXXXXX,TB,2019-04-11 00:00:00,18-19,U
10,1955,F,RP,NL,1955,XXXXXXXXXXX,TB,2019-04-15 00:00:00,55-59,PP
11,2561,F,AV,Wlg,2561,XXXXXXXXXXX,TB,2019-07-09 00:00:00,40-44,M
12,2875,F,AV,AM,2875,XXXXXXXXXXX,TB,2019-09-06 00:00:00,50-54,U

In [7]:
frame=[dtf1,dtf2]
dtf=pd.concat(frame)

In [8]:
#dtf=dtf.drop("Unnamed: 0",axis=1)

In [9]:
dtf['Applied']=dtf['Applied'].replace(r'',np.NaN)
dtf.dropna()
dtf['Applied']=dtf['Applied'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Applied']=dtf['Applied'].astype(float)

dtf['Received']=dtf['Received'].replace(r'',np.NaN)
dtf.dropna()
dtf['Received']=dtf['Received'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Received']=dtf['Received'].astype(float)

In [10]:
'''
dtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')
dtf['Year'] = pd.DatetimeIndex(dtf['Date']).year
dtf['Month'] = pd.DatetimeIndex(dtf['Date']).month
dtf['Day']= pd.DatetimeIndex(dtf['Date']).day
dtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)
dtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear
'''

"\ndtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')\ndtf['Year'] = pd.DatetimeIndex(dtf['Date']).year\ndtf['Month'] = pd.DatetimeIndex(dtf['Date']).month\ndtf['Day']= pd.DatetimeIndex(dtf['Date']).day\ndtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)\ndtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear\n"

In [11]:
dtf

,Applied,Gender,Payment_Method,Location,Received,Id,Reason,Date,Age,Area
1,540.0,M,AV,AM,540.00,GHI001236741,RA,4-Oct-17,40-44,M
2,500.0,F,AV,AM,500.00,GHI001236741,RA,13-Oct-17,35-39,M
3,260.0,M,AV,AM,260.00,GHI001236741,RA,18-Jan-18,18-19,M
4,260.0,F,AV,AM,260.00,GHI001236741,RA,26-Jan-18,20-24,M
5,540.0,F,RP,AM,540.00,GHI001236741,RA,5-Nov-18,25-29,M
6,850.0,F,RP,O,850.00,GHI001644816,RA,24-Dec-18,25-29,M
7,620.0,M,AV,O,620.00,GHI001644816,RA,8-Jan-19,35-39,NE
8,840.0,M,RP,AM,840.00,GHI001644816,RA,11-Jan-19,30-34,M
9,560.0,M,AV,BP,560.00,GHI001644816,RA,25-Feb-19,25-29,M
10,640.0,M,AV,BP,640.00,GHI001644816,RA,8-Mar-19,50-54,NE
11,740.0,F,AV,W,740.00,GHI001644816,RA,28-Mar-19,25-29,M
12,720.0,M,AV,BP,720.00,GHI001644816,RA,29-Mar-19,30-34,M
13,570.0,M,AV,BP,570.00,GHI001644816,RA,17-Apr-19,35-39,M
14,640.0,M,AV,O,640.00,GHI001644816,RA,24-Apr-19,40-44,NE
15,1920.0,M,AV,O,1920.00,GHI001644816,RA,14-Jun-19,50-54,NE
16,620.0,M,AV,BP,620.00,GHI001644816,RA,20-Jun-19,35-39,NE
17,660.0,M,AV,BP,660.00,GHI001644816,RA,27-Jun-19,25-29,NE
18,720.0,F,RP,O,720.00,GHI001644816,RA,12-Jul-19,55-59,NE
19,660.0,F,RP,BP,660.00,GHI001644816,RA,18-Jul-19,35-39,M
20,680.0,M,AV,O,680.00,GHI001644816,RA,5-Sep-19,25-29,M
21,278.0,M,AV,AM,278.14,GHI001644816,RA,3-Oct-19,50-54,M
22,680.0,M,AV,BP,680.00,GHI001644816,RA,4-Oct-19,35-39,M
23,602.0,M,AV,AM,601.86,GHI001644816,RA,4-Oct-19,50-54,M
24,740.0,F,AV,BP,740.00,GHI001644816,RA,4-Oct-19,30-34,NE
25,840.0,F,AV,AM,840.00,GHI001644816,RA,12-Nov-19,40-44,M
26,980.0,F,AV,AM,980.00,GHI001644816,RA,14-Nov-19,40-44,M
27,800.0,M,AV,AM,800.00,GHI000183071,RA,9-Jul-18,30-34,M
28,700.0,M,AV,AM,700.00,GHI000183071,RA,11-Oct-18,35-39,U
29,300.0,M,AV,EC,300.00,GHI001211664,RA,14-Sep-17,20-24,U
30,300.0,M,AV,EC,300.00,GHI001211664,RA,12-Dec-17,35-39,M
31,220.0,F,AV,EC,220.00,GHI001211664,RA,22-Mar-18,20-24,NE
32,350.0,M,AV,EC,350.00,GHI001211664,RA,4-May-18,35-39,M
33,335.0,F,AV,EC,335.00,GHI001211664,RA,9-Nov-18,25-29,NE
34,355.0,M,AV,EC,355.00,GHI001211664,RA,13-Nov-18,35-39,O
35,800.0,F,AV,EC,800.00,GHI001211664,RA,10-Dec-18,65+,NE
36,320.0,M,AV,EC,320.00,GHI001211664,RA,13-Dec-18,30-34,NE
37,500.0,M,RP,O,500.00,GHI001211664,RA,21-Dec-18,35-39,M
38,900.0,F,AV,O,900.00,GHI001211664,RA,4-Jan-19,25-29,M
39,580.0,M,RP,O,580.00,GHI001211664,RA,7-Jan-19,30-34,NE
40,600.0,M,AV,O,600.00,GHI001211664,RA,9-Jan-19,45-49,M
41,640.0,M,AV,O,640.00,GHI001211664,RA,10-Jan-19,60-64,M
42,860.0,F,AV,O,860.00,GHI001211664,RA,28-Jan-19,30-34,NE
43,340.0,F,RP,EC,340.00,GHI001211664,RA,20-May-19,20-24,M
1,339.0,M,AV,AM,339.25,XXXXXXXXXXX,CR,2017-02-09 00:00:00,25-29,O
2,950.0,F,AV,C,950.00,XXXXXXXXXXX,CR,2017-02-17 00:00:00,35-39,M
3,1139.0,GD,RP,BP,1138.50,XXXXXXXXXXX,CR,2017-09-29 00:00:00,45-49,M
4,1650.0,M,RP,O,1650.00,XXXXXXXXXXX,RA,2018-05-07 00:00:00,30-34,PP
5,341.0,F,U,W,341.00,XXXXXXXXXXX,RA,2018-11-19 00:00:00,20-24,M
6,2915.0,GD,U,EC,2915.25,XXXXXXXXXXX,RA,2019-02-01 00:00:00,16,NE
7,2599.0,F,AV,T,2599.00,XXXXXXXXXXX,RA,2019-03-13 00:00:00,17,O
8,1783.0,F,AV,N,1782.50,XXXXXXXXXXX,RA,2019-04-10 00:00:00,65+,PP
9,1955.0,F,AV,S,1955.00,XXXXXXXXXXX,TB,2019-04-11 00:00:00,18-19,U
10,1955.0,F,RP,NL,1955.00,XXXXXXXXXXX,TB,2019-04-15 00:00:00,55-59,PP
11,2561.0,F,AV,Wlg,2561.00,XXXXXXXXXXX,TB,2019-07-09 00:00:00,40-44,M
12,2875.0,F,AV,AM,2875.00,XXXXXXXXXXX,TB,2019-09-06 00:00:00,50-54,U

In [12]:
mapper = {"16" : "Teenage", "17" : "Teenage", "18-19" : "Adult", "20-24": "Adult",
          "25-29" : "Adult", "30-34" : "MidAge", "35-39" : "MidAge", "40-44" : "MidAge",
          "45-49" : "MidAge", "50-54" : "Old", "55-59" : "Old", "60-64" : "Old", "65+":"Old"}

In [13]:
dtf["AgeGroup"] = dtf["Age"].map(mapper)

In [14]:
pmapper = {"AV":"AV","RP":"RPU", "U":"RPU"}

In [15]:
dtf["Payment_Type"] = dtf["Payment_Method"].map(pmapper)

In [16]:
dtf["logapplied"] = pd.Series(np.log(dtf["Applied"]), index = dtf.index)
dtf["logreceived"] = pd.Series(np.log(dtf["Received"]), index = dtf.index)

In [17]:
def add_datepart(df, fldname, drop=True):
    fld = df[fldname]
    if not np.issubdtype(fld.dtype, np.datetime64):
        df[fldname] = fld = pd.to_datetime(fld, infer_datetime_format=True)
    targ_pre = re.sub('[Dd]ate$', '', fldname)
    for n in ('Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
            'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start'):
        df[targ_pre+n] = getattr(fld.dt,n.lower())
    df[targ_pre+'Elapsed'] = fld.astype(np.int64) // 10**9
    if drop: df.drop(fldname, axis=1, inplace=True)

In [18]:
add_datepart(dtf, "Date")

<ipython-input-17-aa99c3778298>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df[targ_pre+n] = getattr(fld.dt,n.lower())

In [19]:
dtf.columns

Index(['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Age', 'Area', 'AgeGroup', 'Payment_Type', 'logapplied',
       'logreceived', 'Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
       'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start',
       'Is_year_end', 'Is_year_start', 'Elapsed'],
      dtype='object')

In [20]:
dataf=dtf.copy()

In [21]:
#del dataf['Date']
del dataf['Gender']
del dataf['Id']
del dataf['Applied']
del dataf['Received']
del dataf['Age']
del dataf['Reason']
del dataf['Payment_Method']
## Removed highly correlated KPIS
#del dataf["Week_Of_Month"]
#del dataf["Week_Of_Year"]
del dataf['logreceived']
#del dataf['Ratio']
del dataf['Dayofweek']
#del dataf['Dayofyear']
del dataf['Is_month_end']
del dataf['Is_month_start']
del dataf['Is_quarter_end']
del dataf['Is_quarter_start']
del dataf['Is_year_end']
del dataf['Is_year_start']

In [22]:
dataf=pd.get_dummies(dataf,drop_first=True)

dataf

,logapplied,Year,Month,Week,Day,Dayofyear,Elapsed,Location_BP,Location_C,Location_EC,...,Location_W,Location_Wlg,Area_NE,Area_O,Area_PP,Area_U,AgeGroup_MidAge,AgeGroup_Old,AgeGroup_Teenage,Payment_Type_RPU
1,6.291569,2017,10,40,4,277,1507075200,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,6.214608,2017,10,41,13,286,1507852800,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,5.560682,2018,1,3,18,18,1516233600,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5.560682,2018,1,4,26,26,1516924800,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6.291569,2018,11,45,5,309,1541376000,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,6.745236,2018,12,52,24,358,1545609600,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,6.429719,2019,1,2,8,8,1546905600,0,0,0,...,0,0,1,0,0,0,1,0,0,0
8,6.733402,2019,1,2,11,11,1547164800,0,0,0,...,0,0,0,0,0,0,1,0,0,1
9,6.327937,2019,2,9,25,56,1551052800,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10,6.461468,2019,3,10,8,67,1552003200,1,0,0,...,0,0,1,0,0,0,0,1,0,0
11,6.606650,2019,3,13,28,87,1553731200,0,0,0,...,1,0,0,0,0,0,0,0,0,0
12,6.579251,2019,3,13,29,88,1553817600,1,0,0,...,0,0,0,0,0,0,1,0,0,0
13,6.345636,2019,4,16,17,107,1555459200,1,0,0,...,0,0,0,0,0,0,1,0,0,0
14,6.461468,2019,4,17,24,114,1556064000,0,0,0,...,0,0,1,0,0,0,1,0,0,0
15,7.560080,2019,6,24,14,165,1560470400,0,0,0,...,0,0,1,0,0,0,0,1,0,0
16,6.429719,2019,6,25,20,171,1560988800,1,0,0,...,0,0,1,0,0,0,1,0,0,0
17,6.492240,2019,6,26,27,178,1561593600,1,0,0,...,0,0,1,0,0,0,0,0,0,0
18,6.579251,2019,7,28,12,193,1562889600,0,0,0,...,0,0,1,0,0,0,0,1,0,1
19,6.492240,2019,7,29,18,199,1563408000,1,0,0,...,0,0,0,0,0,0,1,0,0,1
20,6.522093,2019,9,36,5,248,1567641600,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5.627621,2019,10,40,3,276,1570060800,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,6.522093,2019,10,40,4,277,1570147200,1,0,0,...,0,0,0,0,0,0,1,0,0,0
23,6.400257,2019,10,40,4,277,1570147200,0,0,0,...,0,0,0,0,0,0,0,1,0,0
24,6.606650,2019,10,40,4,277,1570147200,1,0,0,...,0,0,1,0,0,0,1,0,0,0
25,6.733402,2019,11,46,12,316,1573516800,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,6.887553,2019,11,46,14,318,1573689600,0,0,0,...,0,0,0,0,0,0,1,0,0,0
27,6.684612,2018,7,28,9,190,1531094400,0,0,0,...,0,0,0,0,0,0,1,0,0,0
28,6.551080,2018,10,41,11,284,1539216000,0,0,0,...,0,0,0,0,0,1,1,0,0,0
29,5.703782,2017,9,37,14,257,1505347200,0,0,1,...,0,0,0,0,0,1,0,0,0,0
30,5.703782,2017,12,50,12,346,1513036800,0,0,1,...,0,0,0,0,0,0,1,0,0,0
31,5.393628,2018,3,12,22,81,1521676800,0,0,1,...,0,0,1,0,0,0,0,0,0,0
32,5.857933,2018,5,18,4,124,1525392000,0,0,1,...,0,0,0,0,0,0,1,0,0,0
33,5.814131,2018,11,45,9,313,1541721600,0,0,1,...,0,0,1,0,0,0,0,0,0,0
34,5.872118,2018,11,46,13,317,1542067200,0,0,1,...,0,0,0,1,0,0,1,0,0,0
35,6.684612,2018,12,50,10,344,1544400000,0,0,1,...,0,0,1,0,0,0,0,1,0,0
36,5.768321,2018,12,50,13,347,1544659200,0,0,1,...,0,0,1,0,0,0,1,0,0,0
37,6.214608,2018,12,51,21,355,1545350400,0,0,0,...,0,0,0,0,0,0,1,0,0,1
38,6.802395,2019,1,1,4,4,1546560000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,6.363028,2019,1,2,7,7,1546819200,0,0,0,...,0,0,1,0,0,0,1,0,0,1
40,6.396930,2019,1,2,9,9,1546992000,0,0,0,...,0,0,0,0,0,0,1,0,0,0
41,6.461468,2019,1,2,10,10,1547078400,0,0,0,...,0,0,0,0,0,0,0,1,0,0
42,6.756932,2019,1,5,28,28,1548633600,0,0,0,...,0,0,1,0,0,0,1,0,0,0
43,5.828946,2019,5,21,20,140,1558310400,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,5.826000,2017,2,6,9,40,1486598400,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,6.856462,2017,2,7,17,48,1487289600,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,7.037906,2017,9,39,29,272,1506643200,1,0,0,...,0,0,0,0,0,0,1,0,0,1
4,7.408531,2018,5,19,7,127,1525651200,0,0,0,...,0,0,0,0,1,0,1,0,0,1
5,5.831882,2018,11,47,19,323,1542585600,0,0,0,...,1,0,0,0,0,0,0,0,0,1
6,7.977625,2019,2,5,1,32,1548979200,0,0,1,...,0,0,1,0,0,0,0,0,1,1
7,7.862882,2019,3,11,13,72,1552435200,0,0,0,...,0,0,0,1,0,0,0,0,1,0
8,7.486053,2019,4,15,10,100,1554854400,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9,7.578145,2019,4,15,11,101,1554940800,0,0,0,...,0,0,0,0,0,1,0,0,0,0
10,7.578145,2019,4,16,15,105,1555286400,0,0,0,...,0,0,0,0,1,0,0,1,0,1
11,7.848153,2019,7,28,9,190,1562630400,0,0,0,...,0,1,0,0,0,0,1,0,0,0
12,7.963808,2019,9,36,6,249,1567728000,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [23]:
dataf.columns

Index(['logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear', 'Elapsed',
       'Location_BP', 'Location_C', 'Location_EC', 'Location_N', 'Location_NL',
       'Location_O', 'Location_S', 'Location_T', 'Location_W', 'Location_Wlg',
       'Area_NE', 'Area_O', 'Area_PP', 'Area_U', 'AgeGroup_MidAge',
       'AgeGroup_Old', 'AgeGroup_Teenage', 'Payment_Type_RPU'],
      dtype='object')

In [24]:
Xx=dataf[['logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear', 'Elapsed',
       'Location_BP', 'Location_C', 'Location_EC', 'Location_N', 'Location_NL',
       'Location_O', 'Location_S', 'Location_T', 'Location_W', 'Location_Wlg',
       'Area_NE', 'Area_O', 'Area_PP', 'Area_U', 'AgeGroup_MidAge',
       'AgeGroup_Old', 'AgeGroup_Teenage', 'Payment_Type_RPU']]

# Logistic Regression

In [25]:
sc = pickle.load(open('scaler1.sav','rb'))
Xx = sc.transform(Xx)

In [26]:
loaded_model = pickle.load(open('LR_trained_model.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred = loaded_model.predict(Xx)

# D Classifier

In [27]:
loaded_model = pickle.load(open('Binary_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred2 = loaded_model.predict(Xx)

In [28]:
Ypred2

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# Random Forest

In [29]:
loaded_model = pickle.load(open('Random_Forest_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred3 = loaded_model.predict(Xx)

In [30]:
Ypred3

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

# Voting Classifier

In [31]:
loaded_model = pickle.load(open('Voting_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred4 = loaded_model.predict(Xx)

In [32]:
Ypred4

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

# Saving prediction in an excel file

In [34]:
prediction1 = pd.DataFrame(Ypred, columns=['predictionsLR'])
prediction2 = pd.DataFrame(Ypred2, columns=['predictionsBC'])
prediction3 = pd.DataFrame(Ypred3, columns=['predictionsRFC'])
prediction4 = pd.DataFrame(Ypred4, columns=['predictionsVC'])

frames=[dtf1,prediction1,prediction2,prediction3,prediction4]

result = pd.concat(frames,axis=1)

In [35]:
result.to_excel("Prediction_Suspected_List.xlsx")